[versions]
night-config = "3.9.0"
jspecify = "1.0.1"

[libraries]
night-config-core = { module = "com.electronwill.night-config:core", version.ref = "night-config" }
night-config-toml = { module = "com.electronwill.night-config:toml", version.ref = "night-config" }

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
